# Generated by Django 3.1.5 on 2021-01-10 10:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all', '0002_personal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='personal',
            name='email',
            field=models.EmailField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='personal',
            name='phone',
            field=models.IntegerField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Incorrect phone number format.', regex='^\\+?1?\\d{7,10}$')]),
        ),
    ]
