# Generated by Django 3.1.5 on 2021-01-11 07:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all', '0004_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='photo',
            field=models.FileField(blank=True, upload_to='uploads'),
        ),
        migrations.AlterField(
            model_name='personal',
            name='phone',
            field=models.IntegerField(unique=True, validators=[django.core.validators.RegexValidator(message='Incorrect phone number format.', regex='^\\+?1?\\d{7,10}$')]),
        ),
    ]
