# Generated by Django 3.1.5 on 2021-01-11 09:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all', '0005_auto_20210111_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='phone',
            field=models.IntegerField(blank=True, unique=True, validators=[django.core.validators.RegexValidator(message='Incorrect phone number format.', regex='^\\+?1?\\d{7,10}$')]),
        ),
        migrations.AlterField(
            model_name='personal',
            name='photo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
