# Generated by Django 3.1.5 on 2021-01-12 02:09

import all.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all', '0009_education'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='to_year',
            field=models.PositiveIntegerField(blank=True, default=2021, validators=[django.core.validators.MinValueValidator(1984), all.models.max_value_current_year]),
        ),
    ]
