# Generated by Django 3.1.5 on 2021-01-12 03:05

import all.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('all', '0010_auto_20210112_1509'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.TextField()),
                ('organization', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='education',
            name='to_year',
            field=models.PositiveIntegerField(blank=True, default=2021, validators=[all.models.max_value_current_year]),
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField()),
                ('exp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='all.experience')),
            ],
        ),
    ]
