# Generated by Django 3.1.5 on 2021-01-12 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all', '0011_auto_20210112_1605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='desc',
        ),
        migrations.AddField(
            model_name='list',
            name='description',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='experience',
            name='organization',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='experience',
            name='position',
            field=models.CharField(max_length=500),
        ),
    ]
