# Generated by Django 3.1.5 on 2021-01-19 00:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('all', '0012_auto_20210112_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='from_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experience',
            name='to_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
