# Generated by Django 3.1.5 on 2021-01-19 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('all', '0016_auto_20210120_0836'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
    ]
