# Generated by Django 3.1.5 on 2021-01-19 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('all', '0018_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='category_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='all.category'),
        ),
    ]
