# Generated by Django 3.1.5 on 2021-01-19 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('all', '0019_project_category_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='category_id',
            new_name='category',
        ),
    ]
