# Generated by Django 3.1.5 on 2021-01-19 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all', '0021_project_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='link',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
