# Generated by Django 3.1.5 on 2021-01-19 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all', '0022_project_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='link',
            field=models.CharField(max_length=500),
        ),
    ]
